[bot]
name = "go"
message = "Hello. I'm a group bot. If you don't understand the following, you probably don't need me. Привет. Это - бот группы Rоссийская Fедерация. Цель - объединить и обеспечить общение русскоязычных пользователей Федиверса. Работает так: если хочешь в группу - подпишись на меня, а потом напиши мне что-нибудь, а я это бустану. Все, кто на меня подписан, увидят твое сообщение. Если хочешь связаться с админом, отправь мне директ."
message_welcome = "В нашей группе новый подписчик. Прошу любить и жаловать, "


[response]
visibility = "public"
delay = 3

[mastodon]
server= "https://mastodon.wrk.ru"
clientId= "bcc80ae1eb821f01ac141614700f066d18a338a2be9873f60ab1226904594ff8"
clientSecret= "6df0d2c14ec704ab0148f094390891f6f5ed4479e7f9d0909419b7638e425d39"
accessToken= "c9282296bdfff6c87727bc67c2a95a3749f2011115b681654ec215a1c51fd7fb"
